# Generated by Django 3.1.14 on 2023-05-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
    ]
